### ISSUE TITLE
Are u here guys ?

### ISSUE THREAD

**Issue by NguyenTanPhat10a13pn** [nhom7PN/L-p-10a13-nh-m-7#3]

**Comment by NguyenXuanPhong10a13pn** [comment]
I'm here!!!

**Comment by nguyenminhduc10a13PN** [comment]
here guys

**Comment by nguyenminhduc10a13PN** [comment]
sr i'm in toilet for a while

**Comment by nguyenminhduc10a13PN** [comment]
now i'm here

**Comment by NguyenTanPhat10a13pn** [comment]
my leader, @nguyenminhduc10a13PN , have been in toilet for a long time so he can't reply your chat @HienCaoPhuNhuan we sorry for our delaying ; - ;

**Comment by HienCaoPhuNhuan** [comment]
> my leader, @nguyenminhduc10a13PN , have been in toilet for a long time so he can't reply your chat @HienCaoPhuNhuan we sorry for our delaying ; - ; 

Vẫn còn thiếu thành viên

**Comment by nguyenminhduc10a13PN** [comment]
where Huy?

**Comment by NguyenTuanHuy10a13pn** [comment]
Dạ xin lỗi thầy giờ con mới có mạng để nhắn

**Comment by NguyenTanPhat10a13pn** [comment]
@Daoanhthu2711 where r u ?
