### ISSUE TITLE
alooooooooooooooooooooooooooooooo

### ISSUE THREAD

**Issue by nguyenminhduc10a13PN** [nhom7PN/L-p-10a13-nh-m-7#7]
mng cb tí làm bài nkaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by NguyenTanPhat10a13pn** [comment]
OK

**Comment by NguyenTanPhat10a13pn** [comment]
đóng giùm mấy cái issuse kia đi @nguyenminhduc10a13PN  @_@

**Comment by NguyenTuanHuy10a13pn** [comment]
Chào mọi người :>

**Comment by NguyenTuanHuy10a13pn** [comment]
Ông chưa đóng issue kìa Đức ơi

**Comment by HienCaoPhuNhuan** [comment]
@nguyenminhduc10a13PN sao con xóa project 4 rồi

**Comment by NguyenTanPhat10a13pn** [comment]
@HienCaoPhuNhuan project bài 4 còn bên project ngoài ấy thầy

**Comment by HienCaoPhuNhuan** [comment]
> @HienCaoPhuNhuan project bài 4 còn bên project ngoài ấy thầy 

Ko có, chụp lại thầy xem

**Comment by NguyenTanPhat10a13pn** [comment]
![image](https://user-images.githubusercontent.com/91664949/141230884-13c82eb6-9062-4009-bb4b-1117ba0905c2.png)

**Comment by HienCaoPhuNhuan** [comment]
@NguyenTanPhat10a13pn Mốt tạo hẳn project trong repository L-p-10a13-nh-m-7 này luôn nha, lúc tạo repository là mấy đứa làm thừa bước rồi

**Comment by NguyenTanPhat10a13pn** [comment]
tạo trong đó ko cho thành viên chỉnh sửa  thầy ơi @_@

**Comment by HienCaoPhuNhuan** [comment]
> tạo trong đó ko cho thành viên chỉnh sửa thầy ơi @_@

làm thừa bước dẫn đến sự phức tạp như giờ nè thấy chưa

**Comment by nguyenminhduc10a13PN** [comment]
huhuhuhuhuhu

**Comment by nguyenminhduc10a13PN** [comment]
giờ mỗi bạn làm 1 câu nha
mỗi bài sẽ có 2 đến 3 câu
các bạn tự phân chia công việc rõ ràng hợp lí để tránh dẫn đến sai sót nhé
chúc các bạn một ngày tốt lành

**Comment by NguyenTanPhat10a13pn** [comment]
xin làm hết bài 5 <3

**Comment by nguyenminhduc10a13PN** [comment]
ô kê nha
giờ là Phát bài 5, Thư bài 8, Huy bài 6, Phong bài 7, còn tui đi làm tông hợp báo cáo
ô kê thế là thống nhất nhé, không ai phàn nàn gì thì chốt deal nha các cậu:))

**Comment by NguyenTuanHuy10a13pn** [comment]
Ủa làm ở đâu tui chưa thấy

**Comment by NguyenTanPhat10a13pn** [comment]
> Ủa làm ở đâu tui chưa thấy

https://github.com/nhom7PN
rồi ấn vào project og : )

**Comment by NguyenTuanHuy10a13pn** [comment]
Tui làm xong rồi mà bài khó quá nên không biết đúng không 😕

**Comment by NguyenTanPhat10a13pn** [comment]
2 bạn kia đâu r nhỉ

**Comment by HienCaoPhuNhuan** [comment]
> Tui làm xong rồi mà bài khó quá nên không biết đúng không 😕

Khó quá sao ko hỏi các bạn

**Comment by NguyenTuanHuy10a13pn** [comment]
Bạn nhóm trưởng nói con cố tra Google thầy ơi :>

**Comment by NguyenTanPhat10a13pn** [comment]
2 người nữa đâu (* ￣︿￣)

**Comment by HienCaoPhuNhuan** [comment]
nhóm có thành viên ít tương tác quá nha, phải trừ điểm mới đc

**Comment by NguyenTuanHuy10a13pn** [comment]
Đừng mà thầyyyyyy

**Comment by NguyenXuanPhong10a13pn** [comment]
Dạ con có mặt thầy đừng trừ ạ ._.

**Comment by nguyenminhduc10a13PN** [comment]
ua gi zzzzzzzzzzzzzzz

**Comment by nguyenminhduc10a13PN** [comment]
đừng trừ điểm thầy ơi 
điểm tin em thấp thế rồi mà thầy:"(((

**Comment by nguyenminhduc10a13PN** [comment]
hic hu hic hu hic hu

**Comment by NguyenTanPhat10a13pn** [comment]
còn one lady nữa đâu  ￣へ￣

**Comment by Daoanhthu2711** [comment]
mình đay mng

**Comment by nguyenminhduc10a13PN** [comment]
m gắn đuôi ốc sên hã

**Comment by nguyenminhduc10a13PN** [comment]
chậm dữ z mèn đéc ơi

**Comment by Daoanhthu2711** [comment]
tuần này mấy bài kia làm trc iiii

**Comment by nguyenminhduc10a13PN** [comment]
làm r mà

**Comment by NguyenTanPhat10a13pn** [comment]
làm bài 8 đi t còn làm báo cáo (* ￣︿￣)

**Comment by Daoanhthu2711** [comment]
đng làm neee
